#!/bin/bash
SESSION=$USER

DEVELOPMENT_WINDOW=1

REMOTE_WINDOW=2

. SetUpRaspPiZeroEnv

tmux -2 new-session -d -s $SESSION

# Setup a window for tailing log files

tmux new-window -t $SESSION:$DEVELOPMENT_WINDOW -n 'Development'


tmux new-window -t $SESSION:$REMOTE_WINDOW -n 'Remote'
tmux send-keys "sshpass -p '00512546' ssh pi@192.168.0.122" c-m



# Set default window
tmux select-window -t $SESSION:$DEVELOPMENT_WINDOW

# Attach to session
tmux -2 attach-session -t $SESSION